version: '3.8'

services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydb'
      - 'POSTGRES_PASSWORD=0000'
      - 'POSTGRES_USER=yoona'
    ports:
      - '5432:5432'
    volumes:
      - 'db-data:/var/lib/postgresql/data'
    container_name: 'today_db'

volumes:
  db-data: