version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0000

    ports:
      - "5432:5432"
    volumes:
      - 'db-data:/var/lib/postgresql/data'
    container_name: 'today_db'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d mydb" ]

      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/mydb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 0000


volumes:
  db-data:
